title: Read The Docs Jekyll Theme
description: Port of the Read the Docs theme to Jekyll to use with GitHub Pages.
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: ProCat Solutions Kft.
repo_url: "https://github.com/FKMLJF/net-front-wrapper"
edit_on_github: false
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: false
hljs_style: github-gist
